### PR TITLE
refactor: model_meta_dirty to use Set ( )

### PR DESCRIPTION
**Pull request by WongYC-66**
Related Issue : [here](https://github.com/pockettojs/pocketto/issues/5)

Test result : 
image

### CODE REVIEW

**Review by kentng201 — APPROVED** [review]

**Comment by kentng201** [comment]
This one is good, next one can consider to refactor _before_dirty field to set, it is the same

**Comment by WongYC-66** [comment]
Is this function designed to return true as long as  there is 1 attribute added? 

```
 isDirty(attribute?: ModelKey<this>): boolean {
        return this._meta._dirty.size !== 0 || this._meta._dirty.has(attribute as string);
 }
```

If this function return False only when it has no attribute added.

Consider this
```
 isDirty(attribute?: ModelKey<this>): boolean {
        return this._meta._dirty.size > 0
 }
```

in this case, input is already NOT relevant, further refactor
```
 isDirty(): boolean {
        return this._meta._dirty.size > 0
 }
```

futher thought is that maybe this don't even need to be a set at all, just a Boolean
```
this._meta._dirty = false // initialize
this._meta._dirty = true // add attribute

isDirty(): boolean {
        return this._meta._dirty
 }
```

**Comment by kentng201** [comment]
The `isDirty` function is being designed where:
- when 0 parameter is pass, calling model.isDirty(), to check whether the whole model, either of any attribute is being modified before?

- when 1 parameter is pass, calling `model.isDirty('desireAttribute'), to check the 'desireAttribute' is being modified before or not

**Comment by WongYC-66** [comment]
I see, then this PR might have a bug, shall be this:
```
 isDirty(attribute?: ModelKey<this>): boolean {
        return this._meta._dirty.has(attribute as string) || this._meta._dirty.size > 0;
 }
```
I would create another PR for this issue.

**Pull request merged**
